[scrolling]
history = 20000

[font]
size = 10.5

[colors.primary]
foreground = "#d0d0d0"
background = "#000000"

[colors.normal]
black = "#000000"
red = "#d80036"
green = "#00c322"
yellow = "#a68d00"
blue = "#2862e8"
magenta = "#cd0074"
cyan = "#00a287"
white = "#d0d0d0"

[colors.bright]
black = "#555555"
red = "#f93e58"
green = "#9bed00"
yellow = "#ffd900"
blue = "#6c8dd5"
magenta = "#e83a93"
cyan = "#5ed0bd"
white = "#ffffff"

[bell]
duration = 60

[selection]
save_to_clipboard = true

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
command = "xdg-open"
post_processing = true

[hints.enabled.mouse]
enabled = true
mods = "Control"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[[mouse.bindings]]
mouse = "Back"
action = "Paste"
