#!/usr/bin/env fish

set exit_status 0

function mk-link -a link -a target
    mkdir -p -- (dirname -- $link)
    if not set -l current (readlink -- $link); or test $current != $target
        if not ln -sT -- $target $link
            set exit_status 1
        end
    end
end

set dir (dirname -- (realpath -- (status filename)))

function mk-plain-link -a path
    mk-link ~/$path $dir/$path
end

function mk-dot-link -a path
    mk-link ~/.$path $dir/$path
end

mk-plain-link bin/bash-source-env-diff
mk-plain-link bin/calc-replay-gain
if test -x /usr/bin/discord
    mk-plain-link bin/discord
end
if test -x /usr/bin/element-desktop
    mk-plain-link bin/element-desktop
end
mk-plain-link bin/env-diff
mk-plain-link bin/env-dump
if type -fq i3; and type -fq systemctl
    mk-plain-link bin/i3-session
end
mk-plain-link bin/org-music
if test -x /usr/bin/psst-gui
    mk-plain-link bin/psst-gui
end
mk-plain-link bin/rgit
mk-plain-link bin/rre
if type -fq feh
    mk-plain-link bin/wallpaper
end
if type -fq xsettingsd
    mk-plain-link bin/xsettingsd-auto-dpi
end

mk-link ~/bin/git-reparent $dir/bin/git-reparent/git-reparent

if set x_terminal_emulator ( \
        type -fp alacritty 2>/dev/null; or \
        type -fp urxvt 2>/dev/null; or \
        type -fp xterm 2>/dev/null)
    mk-link ~/bin/x-terminal-emulator $x_terminal_emulator
end

mk-dot-link Xresources
mk-dot-link config/1Password/settings/settings.json
mk-dot-link config/RawTherapee/profiles/default.pp3
mk-dot-link config/alacritty/alacritty.toml
mk-dot-link config/bat/config
mk-dot-link config/chrome-flags.conf
mk-dot-link config/fish/config.fish
mk-dot-link config/fish/functions
mk-dot-link config/fontconfig/fonts.conf
mk-dot-link config/git/config
mk-dot-link config/git/config-parity
mk-dot-link config/git/ignore-global
mk-dot-link config/gtk-3.0/settings.ini
mk-dot-link config/mimeapps.list
mk-dot-link config/msmtp/config
mk-dot-link config/msmtp/gmail-password.gpg
mk-dot-link config/picom/picom.conf
mk-dot-link config/profile-env
mk-dot-link config/python/startup.py
mk-dot-link config/spotify-flags.conf
mk-dot-link config/systemd/user/geoclue-agent.service
mk-dot-link config/systemd/user/graphical-apps.target
mk-dot-link config/systemd/user/i3-session.target
mk-dot-link config/systemd/user/i3.service
mk-dot-link config/systemd/user/lxpolkit.service
mk-dot-link config/systemd/user/picom.service
mk-dot-link config/systemd/user/redshift.service
mk-dot-link config/systemd/user/wallpaper.service
mk-dot-link config/systemd/user/xsettingsd-auto-dpi.service
mk-dot-link config/systemd/user/xss-lock.service
mk-dot-link config/user-dirs.dirs
mk-dot-link config/xfce4/helpers.rc
mk-dot-link config/zathura/zathurarc
mk-dot-link gnupg/gpg-agent.conf
mk-dot-link gnupg/scdaemon.conf
mk-dot-link gtkrc-2.0
if test -x /usr/bin/discord
    mk-dot-link local/share/applications/discord.desktop
end
if test -x /usr/bin/element-desktop
    mk-dot-link local/share/applications/io.element.Element.desktop
end
mk-dot-link mailrc
mk-dot-link parallel/will-cite
mk-dot-link profile
mk-dot-link ssh/authorized_keys
mk-dot-link ssh/config
mk-dot-link ssh/parity-yubikey-a.pub
mk-dot-link vim
mk-dot-link xsession

if type -q dconf
    if not dconf load / <$dir/config/dconf/user.txt
        set exit_status 1
    end
end

if type -q systemctl
    if not systemctl --user --quiet enable graphical-apps.target
        set exit_status 1
    end
end

exit $exit_status
