#!/usr/bin/env fish

set exit_status 0

function mk-link -a link -a target
    mkdir -p (dirname $link)
    if not set -l current (readlink $link); or test $current != $target
        if not ln -sT $target $link
            set exit_status 1
        end
    end
end

set dir (dirname (readlink -e (status current-filename)))

function mk-plain-link -a path
    mk-link ~/$path $dir/$path
end

function mk-dot-link -a path
    mk-link ~/.$path $dir/$path
end

mkdir -p ~/.ssh/master

mk-plain-link bin/bash-source-env-diff
mk-plain-link bin/env-diff
mk-plain-link bin/env-dump
mk-plain-link bin/rre

mk-dot-link Xdefaults
mk-dot-link Xresources
mk-dot-link bashrc
mk-dot-link config/fish
mk-dot-link config/fontconfig
mk-dot-link gitconfig
mk-dot-link gitignore-global
mk-dot-link parallel/will-cite
mk-dot-link profile
mk-dot-link ssh/config
mk-dot-link vim
mk-dot-link vimrc

exit $exit_status
