#!/usr/bin/env bash

set -e

dir="$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")"
mk-link() {
    if [[ "$(readlink -e ~/."$1")" != "$dir/$1" ]]; then
        ln -sT "$dir/$1" ~/."$1"
    fi
}

mk-link bashrc
mk-link config
mk-link gitconfig
mk-link gitignore-global
mk-link profile
mk-link vim
mk-link vimrc
